### ISSUE TITLE
Bump regex-cache

### ISSUE THREAD

**Issue by mattdesl** [jonschlinkert/micromatch#21]
micromatch@2.1.5 depends on regex-cache@0.3.0 which is now a little outdated. Darn that magic zero.

:smile: 

I can submit a PR but I figure you may know best whether or not it's safe to bump without major change.

**Comment by jonschlinkert** [comment]
lol, yeah that zero will bite you sometimes. 

> can submit a PR

that would be great, thanks!

**Comment by mattdesl** [comment]
Unfortunately it seems to break a few tests. 

```
184 passing (149ms)
  2 pending
  10 failing

  1) .makeRe() options should match dotfiles when `dotfile` is true::
     AssertionError: expected true to be false
      at Context.<anonymous> (test/makeRe.js:215:68)

  2) .match() paths/filenames: should match files with the given extension::

      AssertionError: expected [ '.md' ] to equal [] (at length, A has 1 and B has 0)
      + expected - actual

      +[]
      -[
      -  ".md"
      -]
      
      at Context.<anonymous> (test/match.js:140:48)

  3) .match() paths/filenames: should not match dotfiles when `dot` or `dotfiles` are not set::

      AssertionError: expected [ '.x.md' ] to equal [] (at length, A has 1 and B has 0)
      + expected - actual

      +[]
      -[
      -  ".x.md"
      -]
      
      at Context.<anonymous> (test/match.js:151:42)

  4) .match() double stars: should match paths with leading `./`::

      AssertionError: expected [ './a/b/c/d/e/z/x.md' ] to equal [] (at length, A has 1 and B has 0)
      + expected - actual

      +[]
      -[
      -  "./a/b/c/d/e/z/x.md"
      -]
      
      at Context.<anonymous> (test/match.js:211:62)

  5) negation patterns .match() should negate dotfiles::

      AssertionError: expected [] to equal [ '.dotfile.md' ] (at length, A has 0 and B has 1)
      + expected - actual

      +[
      +  ".dotfile.md"
      +]
      -[]
      
      at Context.<anonymous> (test/negation.js:35:49)

  6) options.flags should support the `flags` option::

      AssertionError: should not match a file extension
      + expected - actual

      +[]
      -[
      -  "a/b/c/e.md"
      -]
      
      at Context.<anonymous> (test/options.js:25:51)

  7) options.nocase should support the `nocase` option::

      AssertionError: should not match a dirname
      + expected - actual

      +[]
      -[
      -  "a/b/d/e.md"
      -]
      
      at Context.<anonymous> (test/options.js:32:51)

  8) options.nocase should use correct flags when `flags` and `nocase` are used (no double `i`)::

      AssertionError: should not match a dirname
      + expected - actual

      +[]
      -[
      -  "a/b/d/e.md"
      -]
      
      at Context.<anonymous> (test/options.js:42:51)

  9) options.dotfiles: when `dot` or `dotfile` is true: should use negation patterns on dotfiles::

      AssertionError: expected [ 'c' ] to equal [ '.a', '.b', 'c' ] (at length, A has 1 and B has 3)
      + expected - actual

       [
      +  ".a"
      +  ".b"
         "c"
       ]
      
      at Context.<anonymous> (test/options.js:125:58)

  10) micromatch string patterns options should support the `nocase` option::

      AssertionError: expected [ 'a/b/c/e.md' ] to equal [] (at length, A has 1 and B has 0)
      + expected - actual

      +[]
      -[
      -  "a/b/c/e.md"
      -]
      
      at Context.<anonymous> (test/pattern-string.js:223:47)



npm ERR! Test failed.  See above for more details.
```

**Comment by mattdesl** [comment]
With regex-cache@0.3.0 I still have 2 pending, but no failures:

```
  194 passing (148ms)
  2 pending
```

**Comment by jonschlinkert** [comment]
hmmm, this might be why I didn't merge lol. trying to remember. It's also possible that I changed the signature/args in some way. I can look into it, thanks for giving it a shot

**Comment by sethkinast** [comment]
I believe https://github.com/jonschlinkert/is-equal-shallow/pull/1 is the cause of the failing tests.

**Comment by doowb** [comment]
Fixed and bumped with latest dependencies.
